CREATE TABLE `ptv` (
  `id` BIGINT(20) UNSIGNED NOT NULL AUTO_INCREMENT,
  `houseid` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор дома. Параметр отображается в ответе',
  `PhNumber` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Номер стационарного телефона.',
  `Tech` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие Охранно-Пожарной Сигнализации. 0 - ОПС отсутствует, 1 - наличие услуги',
  `WrongList` TINYINT(2) UNSIGNED NULL DEFAULT NULL COMMENT 'Дополнительные данные о телефонной линии. 0 - дополнительные данные отсутствуют. 1 - юридическое лицо. 2 - наличие ИКМ (оборудования уплотнения). 3 - спаренный телефон. 99 - Комстар.',
  `ADSLReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие АДСЛ оборудования на станции. 0 - отсутствие. 1 - наличие.',
  `OrderExists` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки МГТС (PPPoE-ADSL) в АСРЗ 200 не на конечном этапе. 0 - отсутствие. 1 - наличие.',
  `OrderExists208` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки МГТС (Канальная Медь) в АСРЗ 208 не на конечном этапе. 0 - отстствие. 1 - наличие.',
  `TCaseReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения высокоскоростных тарифных планов для ADSL (ТШ). 0 - недоступно. 1 - доступно',
  `OrderID` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Номер активной заявки МГТС (PPPoE-ADSL) в АСРЗ 200',
  `OrderTariff` VARCHAR(100) NULL DEFAULT NULL COMMENT 'Идентификатор тарифного плана в заявке "Лимонка" в АСРЗ 208',
  `ATSHReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность переключения абонента на технологию АТШ. 0 - недоступно. 1 - доступно',
  `OnlyVoiceReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения услуг при переключении абонента на технологию АТШ. 0 - недоступно. 1 - доступно',
  `PONReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность переключения абонента на технологию PON. 0 - недоступно. 1 - доступно',
  `ConstructInfo` TEXT NULL COMMENT 'Текстовое сообщение с информацией о стройке, полученной из системы ПК УКС.',
  `ConstructDateEnd` DATE NULL DEFAULT NULL COMMENT 'Параметр содержит дату окончания стройки, полученную из системы ПК УКС',
  `AddressID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор адреса объекта (внутренний ID базы АСРЗ до квартиры)',
  `PONOrderID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Номер активной заявки "Канальная PON" в АСРЗ 200',
  `PONStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "Канальная PON" В АСРЗ 208 на этапах «Эксплуатация», «Исправление документов», «Инсталляция выполнена», «Ожидание обработки в ГОСЗ» или наличие одной из дочерних заявок на этапе "Эксплуатация". 0 - отсутствие. 1 - наличие',
  `ATSHOrderID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Номер активной заявки "Канальная АТШ" в АСРЗ 200',
  `ATSHStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "Канальная АТШ" в АСРЗ 208 на этапах «Эксп луатация», «Исправление документов», «Инсталляция выполнена», «Ожидание обработки в ГОСЗ» или наличие одной из дочерних заявок на этапе "Эксплуатация". 0 - отсутствие. 1 - наличие',
  `PONOrderStage208` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная PON" в АСРЗ 208.',
  `PONOrderStage200` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная PON" в АСРЗ 200.',
  `ATSHOrderStage208` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная АТШ" в АСРЗ 208.',
  `ATSHOrderStage200` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная АТШ" в АСРЗ 200',
  `OrderIDStage208` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Лимонка" в АСРЗ 208.',
  `OrderIDStage200` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Лимонка" в АСРЗ 200.',
  `FTTBReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность переключения абонента на технологию FTTB. 0 - недоступно. 1 - доступно.',
  `FTTBTVReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения услуги Телевидение по технологии FTTB. 0 - недоступно. 1 - доступно.',
  `CATVReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения услуги Кабельное телевидение. ',
  `CATVOrderID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Номер активной заявки "Канальная КТВ" или "Канальная КТВ (юрики)" в АСРЗ 208.',
  `CATVStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "Канальная КТВ" или "Канальная КТВ (юрики)" в АСРЗ 208 на этапе «Эксплуатация». 0 - отсутствие. 1 - наличие.',
  `CATVStage208` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная КТВ" или "Канальная КТВ (юрики)" в АСРЗ 208.',
  `CATVStage200` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная КТВ" или "Канальная КТВ (юрики)" в АСРЗ 200.',
  `FTTBManagedCommutator` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Признак наличия управляемого коммутатора. 0 - коммутатор неуправляемый. 1 - коммутатор управляемый',
  `FTTBOrderID` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Номер активной заявки "Канальная FTTB" в АСРЗ 200.',
  `FTTBStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "Канальная FTTB" В АСРЗ 208 на этапе «Эксплуатация» или наличие одной из дочерних заявок на этапе "Эксплуатация". 0 -отсутствие. 1 -наличие.',
  `FTTBOrderStage208` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная FTTB" в АСРЗ 208.',
  `FTTBOrderStage200` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная FTTB" в АСРЗ 200',
  `MVNO_Ready` INT(10) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения абоненту услуги MVNO. 0 - недоступно. 1 - доступно',
  `Services` LONGTEXT NULL COMMENT 'Блок содержит подблоки, характеризующие подключенные сервисы абонента. TvADSL Присутствие подблока означает наличие у абонента подключенной услуги Телевидение по технологии ADSL. TvADSLTariff Код тарифного плана заявки "IPTV" в АСРЗ 208. TvADSLStage Идентификатор этапа заявки "IPTV" в АСРЗ 208. InternetPON Присутствие подблока означает наличие у абонента подключенной услуги Интернет по технологии PON. InternetPONTariff Код тарифного плана заявки "Интернет PON" в АСРЗ 208. InternetPONStage Идентификатор этапа заявки "Интернет PON" в АСРЗ 208. PhonePON Присутствие подблока означает наличие у абонента подключенной услуги Телефон по технологии PON. PhonePONTariff Код тарифного плана заявки "Телефон PON" в АСРЗ 208. PhonePONStage Идентификатор этапа заявки "Телефон PON" в АСРЗ 208. TvPON Присутствие подблока означает наличие у абонента подключенной услуги Телевидение по технологии PON. TvPONTariff Код тарифного плана заявки "Телевидение PON" в АСРЗ 208. TvPONStage Идентификатор этапа заявки "Телевидение PON" в АСР',
  `MarketingCategoryCode` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Код маркетинговой категории.',
  `ServiceProvider` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор Узла в системе Foris Fix.',
  `IPDomofonB2BReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения услуги "Домофон" для юридических лиц. 0 - недоступно. 1 - доступно',
  `IPDomofonB2CReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность подключения услуги "Домофон" для физических лиц. 0 - недоступно. 1 - доступно',
  `IPDomofonB2COrderID` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Номер заявки "IPDomofon B2C" в АСРЗ 208',
  `IPDomofonB2CStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "IPDomofon B2C" в АСРЗ 208 на этапе "Эксплуатация". 0 - отсутствие. 1 - наличие',
  `IPDomofonB2CStage208` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "IPDomofon B2C" в АСРЗ 208.',
  `IPDomofonB2CStage200` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "IPDomofon B2C" в АСРЗ 200',
  `IPDomofonB2CHandsetOrderID` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Номер заявки "Телефон" для домофонной трубки в АСРЗ 208.',
  `IPDomofonB2CHandsetStatus` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Наличие заявки "Телефон" для домофонной трубки в АСРЗ. 0 - отсутствие. 1 - наличие.',
  `IPDomofonB2CHandsetStage208` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Телефон" для домофонной',
  `IPDomofonB2CHandsetStage200` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Телефон" для домофонной',
  `UserAttr` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Пользовательский атрибут или признак региональной. 0 - любой регион, кроме Москвы. 1 - Москва',
  `CrossState` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Состояние кросса. Может принимать значения: 0 - технология подключения не PON. 1 - стройка. 2 - принят полностью. 3 - принят без ДРС. 4 - выведен из эксплуатации.',
  `ADSLAddressId` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор адреса абонента, содержащийся в базе АСРЗ. Идентификатор возвращается в ответе, если были обнаружены заявки по схемам: ADSL Std., PPPoE-ADSL в АСРЗ 200, находящиеся не на конечных этапах',
  `PONAddressId` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор адреса абонента, содержащийся в базе АСРЗ. Идентификатор возвращается в ответе, если были обнаружены заявки по схемам: Канальная PON, Канальная PON(юрики) в АСРЗ 200, находящиеся не на конечных этапах',
  `ATSHAddressId` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор адреса абонента, содержащийся в базе АСРЗ. Идентификатор возвращается в ответе, если была обнаружена заявка по схеме Канальная АТШ в АСРЗ 200, находящаяся не на конечном этапе.',
  `FTTBAddressId` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор адреса абонента, содержащийся в базе АСРЗ. Идентификатор возвращается в ответе, если была обнаружена заявка по схеме Канальная FTTB в АСРЗ 200, находящаяся не на конечном этапе',
  `ADSLGtt` LONGTEXT NULL COMMENT 'TROUBLE_DATE Дата создания ГТТ. TROUBLE_DOPINFO_BUSINESS Описание ГТТ для бизнеса. GTT_MOTIV_ID Идентификатор типа ГТТ. GTT_MOTIV_NAME Наименование типа ГТТ. GTT_SERVICE_ID Идентификатор услуги (сервиса), в сфере которой был создан ГТТ. GTT_SERVICE_NAME Наименование услуги (сервиса), в сфере которой был создан ГТТ. GTT_BINDING_MODE_ID Идентификатор режима привязки ТТ к ГТТ. GTT_BINDING_MODE_NAME Наименование режима привязки ТТ к ГТТ. TT_PLANE_DATE Ориентировочная дата решения ГТТ. GTT_INFLUENCE_ON_CONNECT Влияние аварии на подключение. Может принимать значения: 0 - влияние отсутстует. 1 - есть влияние',
  `PONGtt` LONGTEXT NULL COMMENT 'Наличие ГТТ по технологии PON. При наличии ГТТ массив будет содержать краткую информацию о данном ГТТ или о нескольких ГТТ.',
  `ATSHGtt` LONGTEXT NULL COMMENT 'Наличие ГТТ по технологии ATSH. При наличии ГТТ массив будет содержать краткую информацию о данном ГТТ или о нескольких ГТТ.',
  `FTTBGtt` LONGTEXT NULL COMMENT 'Наличие ГТТ по технологии FTTB. При наличии ГТТ массив будет содержать краткую информацию о данном ГТТ или о нескольких ГТТ',
  `PONbrReady` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Доступность переключения абонента на технологию PON (bridge). Может принимать значения: 0 - недоступно. 1 - доступно.',
  `PONbrOrderID` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Номер активной заявки "Канальная PON (bridge)" в АСРЗ 200.',
  `PONbrStatus` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Наличие заявки "Канальная PON (bridge)" В АСРЗ 208 на этапе «Эксплуатация». Может принимать значения: 0 - отсутствие. 1 - наличие.',
  `PONbrStage208` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная PON (bridge)" в АСРЗ 208',
  `PONbrStage200` VARCHAR(50) NULL DEFAULT NULL COMMENT 'Идентификатор этапа заявки "Канальная PON (bridge)" в АСРЗ 200',
  `ClientCategory` VARCHAR(50) NULL DEFAULT NULL COMMENT '???',
  `PONReadyB2C` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT '???',
  `PONReadyB2B` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT '???',
  `PONReadyB2CReason` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT '???',
  `Newbuilding` TINYINT(1) UNSIGNED NULL DEFAULT NULL COMMENT 'Признак "Новостройка". Параметр отображается в ответе только при запросе, содержащем исключительно id дома или домов! Может принимать значения: 0 - указанный id дома не имеет признака "Новостройка". 1 - указанный id дома имеет признак "Новостройка"',
  `event_list_id` BIGINT(20) UNSIGNED NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `event_list_id` (`event_list_id`),
  INDEX `Tech` (`Tech`),
  INDEX `ADSLReady` (`ADSLReady`),
  INDEX `WrongList` (`WrongList`),
  INDEX `OrderExists` (`OrderExists`),
  INDEX `OrderExists208` (`OrderExists208`),
  INDEX `TCaseReady` (`TCaseReady`),
  INDEX `ATSHReady` (`ATSHReady`),
  INDEX `OnlyVoiceReady` (`OnlyVoiceReady`),
  INDEX `AddressID` (`AddressID`),
  INDEX `PONOrderID` (`PONOrderID`),
  INDEX `PONStatus` (`PONStatus`),
  INDEX `ATSHOrderID` (`ATSHOrderID`),
  INDEX `ATSHStatus` (`ATSHStatus`),
  INDEX `PONOrderStage208` (`PONOrderStage208`),
  INDEX `PONOrderStage200` (`PONOrderStage200`),
  INDEX `ATSHOrderStage208` (`ATSHOrderStage208`),
  INDEX `ATSHOrderStage200` (`ATSHOrderStage200`),
  INDEX `OrderIDStage208` (`OrderIDStage208`),
  INDEX `OrderIDStage200` (`OrderIDStage200`),
  INDEX `FTTBReady` (`FTTBReady`),
  INDEX `FTTBTVReady` (`FTTBTVReady`),
  INDEX `CATVReady` (`CATVReady`),
  INDEX `CATVOrderID` (`CATVOrderID`),
  INDEX `CATVStatus` (`CATVStatus`),
  INDEX `CATVStage208` (`CATVStage208`),
  INDEX `CATVStage200` (`CATVStage200`),
  INDEX `FTTBManagedCommutator` (`FTTBManagedCommutator`),
  INDEX `FTTBOrderID` (`FTTBOrderID`),
  INDEX `FTTBStatus` (`FTTBStatus`),
  INDEX `FTTBOrderStage208` (`FTTBOrderStage208`),
  INDEX `FTTBOrderStage200` (`FTTBOrderStage200`),
  INDEX `MVNO_Ready` (`MVNO_Ready`),
  INDEX `IPDomofonB2BReady` (`IPDomofonB2BReady`),
  INDEX `IPDomofonB2CReady` (`IPDomofonB2CReady`),
  INDEX `IPDomofonB2CStatus` (`IPDomofonB2CStatus`),
  INDEX `CrossState` (`CrossState`),
  INDEX `UserAttr` (`UserAttr`),
  INDEX `PONbrReady` (`PONbrReady`),
  INDEX `event_list` (`event_list_id`),
  INDEX `PONReadyB2C` (`PONReadyB2C`),
  INDEX `PONReadyB2B` (`PONReadyB2B`),
  INDEX `PONReadyB2CReason` (`PONReadyB2CReason`)
)
  COLLATE='utf8_general_ci'
  ENGINE=MyISAM
;
